// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkD4bWTiNwIYoZc0NqA-UoRX5XNvbFatQ',
    appId: '1:1009519856106:web:e9eaddd49aeec398a78a93',
    messagingSenderId: '1009519856106',
    projectId: 'seblak-mandji-app',
    authDomain: 'seblak-mandji-app.firebaseapp.com',
    storageBucket: 'seblak-mandji-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcAbkg3BUBhPvwS3rPnh00Z_z6SSg-u9Q',
    appId: '1:1009519856106:android:3d9ca144a81dc6d0a78a93',
    messagingSenderId: '1009519856106',
    projectId: 'seblak-mandji-app',
    storageBucket: 'seblak-mandji-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZTZMNMbwCd8xGMFQJnIfsG8qPIglZOnw',
    appId: '1:1009519856106:ios:d178b3c408485e7da78a93',
    messagingSenderId: '1009519856106',
    projectId: 'seblak-mandji-app',
    storageBucket: 'seblak-mandji-app.appspot.com',
    iosBundleId: 'com.example.seblakMandjiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZTZMNMbwCd8xGMFQJnIfsG8qPIglZOnw',
    appId: '1:1009519856106:ios:d178b3c408485e7da78a93',
    messagingSenderId: '1009519856106',
    projectId: 'seblak-mandji-app',
    storageBucket: 'seblak-mandji-app.appspot.com',
    iosBundleId: 'com.example.seblakMandjiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkD4bWTiNwIYoZc0NqA-UoRX5XNvbFatQ',
    appId: '1:1009519856106:web:a590a3b5fcf13c83a78a93',
    messagingSenderId: '1009519856106',
    projectId: 'seblak-mandji-app',
    authDomain: 'seblak-mandji-app.firebaseapp.com',
    storageBucket: 'seblak-mandji-app.appspot.com',
  );
}
